### ISSUE TITLE
Remote Jenkinsfile Provider takes exception with Subversion SCM

### ISSUE THREAD

**Issue by kepler2-seakr** [jenkinsci/remote-file-plugin#29] opened 2021-03-22 20:36 UTC
When a generated Multibranch Pipeline job is executed that uses a jenkinsfile obtained using Remote Jenkinsfile Provider plug-in, the following occurs early in the run of the generated project:

ERROR: Checkout failed
java.lang.ClassCastException: hudson.scm.SubversionSCM cannot be cast to hudson.plugins.git.GitSCM
	at org.jenkinsci.plugins.workflow.multibranch.extended.scm.ExcludeFromChangeSet$ScmListener.onCheckout(ExcludeFromChangeSet.java:59)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:150)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:155)
	at org.jenkinsci.plugins.workflow.multibranch.extended.scm.ExtendedSCMBinder.create(ExtendedSCMBinder.java:83)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE

**Comment by aytuncbeken** [comment] 2021-04-15 20:28
Hi,

Are you using git or subversion for remote file plugin ?

**Comment by ogal555** [comment] 2021-05-07 10:54
subversion

**Comment by aytuncbeken** [comment] 2021-05-13 17:23
Hey @ogal555 
Found the issue, It was caused by casting. This feature is only possible for Git Scm. Making changes to exclude from subversion. 
I will inform when it is released.

**Comment by aytuncbeken** [comment] 2021-05-13 17:50
Release with 1.16. Please validate

**Comment by aytuncbeken** [comment] 2021-05-28 05:15
Hey @ogal555 
Is it fixed for you ? Please let me know. Otherwise I will close the issye

**Comment by aytuncbeken** [comment] 2021-05-30 07:54
As I couldn't get any feedback, I assume it is working fine. Closing the ticket.

**Closed by aytuncbeken** 2021-05-30 07:54 UTC
Labels: fixed
